### ISSUE TITLE
国际化如何支持两层

### ISSUE THREAD

**Issue by 82318179** [alex8088/tiny-libs#1]
比如我的 语言文件是这样定义的
export default {
    abc:{
    ddd:'hhh'
    }
}

那么我调用的时候就是 localize('abc.ddd' ) 结果读不到内容。

**Comment by alex8088** [comment]
目前仅只支持 { “abc.dd” : "" }，出于性能考虑，这种方式可以考虑支持。

**Comment by alex8088** [comment]
新版本1.1已支持
